# Generated by Django 4.2.24 on 2025-12-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(max_length=255)),
                ('flight_info', models.TextField()),
                ('passenger_name', models.CharField(max_length=255)),
                ('passport_number', models.CharField(max_length=50)),
                ('booking_reference', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
